services:
  db:
    image: postgres:15
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_ROLE} 
      POSTGRES_PASSWORD: ${DB_PASS} 
    ports:
      - "${DOCKER_HOST_DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    depends_on:
      - db 
    env_file:
      - ./configs/.env
    environment:
      DB_HOST: db
    ports:
      - "${DOCKER_HOST_PORT}:${PORT}"
    volumes:
      - ${LOGDIR}:/root/${LOGSDIR}

volumes:
  postgres_data: