services:
  db:
    image: postgres:15
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_ROLE} 
      POSTGRES_PASSWORD: ${DB_PASS} 
    ports:
      - "${DOCKER_HOST_DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: always
    container_name: redis
    ports:
      - "${DOCKER_HOST_REDIS_PORT}:${REDIS_PORT}"

  app:
    build: .
    restart: always
    container_name: authservice
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    ports:
      - "${DOCKER_HOST_PORT}:${PORT}"
    volumes:
      - ${LOGDIR}:/root/${LOGSDIR}
volumes:
  postgres_data: